package chat.rocket.app.db.dao;

/**
 * Created by julio on 24/11/15.
 */
public class RCSettings {
    //TODO: the following are all available configs..need to find a way to read each one...
    /*collection\":\"rocketchat_settings\",\"id\":\"Accounts_RegistrationRequired\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Accounts_EmailVerification\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Accounts_AllowedDomainsList\",\"fields\":{\"value\":\"\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Accounts_OAuth_Facebook\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Accounts_OAuth_Google\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Accounts_OAuth_Github\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Accounts_OAuth_Gitlab\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Accounts_OAuth_Linkedin\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Accounts_OAuth_Meteor\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Accounts_OAuth_Twitter\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Accounts_AllowUserProfileChange\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Accounts_AllowUserAvatarChange\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Accounts_AllowUsernameChange\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Accounts_AllowPasswordChange\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Accounts_RequireNameForSignUp\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"FileUpload_Enabled\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"FileUpload_MaxFileSize\",\"fields\":{\"value\":2097152}}"]
 collection\":\"rocketchat_settings\",\"id\":\"FileUpload_MediaTypeWhiteList\",\"fields\":{\"value\":\"image/*,audio/*,application/pdf,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Site_Url\",\"fields\":{\"value\":\"http://localhost:3000/\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Site_Name\",\"fields\":{\"value\":\"Rocket.Chat\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"API_Analytics\",\"fields\":{\"value\":\"\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"API_Embed\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"API_EmbedDisabledFor\",\"fields\":{\"value\":\"\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Message_AllowEditing\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Message_AllowEditing_BlockEditInMinutes\",\"fields\":{\"value\":0}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Message_AllowDeleting\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Message_AllowPinning\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Message_ShowEditedStatus\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Message_ShowDeletedStatus\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Message_KeepHistory\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Message_MaxAllowedSize\",\"fields\":{\"value\":5000}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Message_ShowFormattingTips\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Message_AudioRecorderEnabled\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Push_debug\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Push_enable\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Push_production\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Push_gcm_project_number\",\"fields\":{\"value\":\"\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Layout_Home_Title\",\"fields\":{\"value\":\"Home\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Layout_Home_Body\",\"fields\":{\"value\":\"Welcome to Rocket.Chat <br> Go to APP SETTINGS -> Layout to customize this intro.\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Layout_Terms_of_Service\",\"fields\":{\"value\":\"Terms of Service <br> Go to APP SETTINGS -> Layout to customize this page.\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Layout_Privacy_Policy\",\"fields\":{\"value\":\"Privacy Policy <br> Go to APP SETTINGS -> Layout to customize this page.\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Layout_Sidenav_Footer\",\"fields\":{\"value\":\"<div><a href=\\\"https://github.com/RocketChat/Rocket.Chat\\\" class=\\\"logo\\\" target=\\\"_blank\\\"> <img src=\\\"/images/logo/logo.svg?v=3\\\" /></a><div class=\\\"github-tagline\\\"><span class=\\\"octicon octicon-pencil\\\" style=\\\"color: #994C00\\\"></span> with <span class=\\\"octicon octicon-heart\\\" style=\\\"color: red\\\"></span> on <span class=\\\"octicon octicon-mark-github\\\"></span></div></div>\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Layout_Login_Header\",\"fields\":{\"value\":\"<a class=\\\"logo\\\" href=\\\"/\\\"><img src=\\\"/images/logo/logo.svg?v=3\\\" /></a>\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Layout_Login_Terms\",\"fields\":{\"value\":\"By proceeding to create your account and use Rocket.Chat, you are agreeing to our <a href=\\\"/terms-of-service\\\">Terms of Service</a> and <a href=\\\"/privacy-policy\\\">Privacy Policy</a>. If you do not agree, you cannot use Rocket.Chat.\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"API_Gitlab_URL\",\"fields\":{\"value\":\"\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"WebRTC_Enable_Channel\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"WebRTC_Enable_Private\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"WebRTC_Enable_Direct\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"API_Wordpress_URL\",\"fields\":{\"value\":\"\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"API_GitHub_Enterprise_URL\",\"fields\":{\"value\":\"\"}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Message_AllowPinningByAnyone\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"Message_AllowStarring\",\"fields\":{\"value\":true}}"]
 collection\":\"rocketchat_settings\",\"id\":\"LDAP_Enable\",\"fields\":{\"value\":false}}"]
 collection\":\"rocketchat_settings\",\"id\":\"LDAP_DN\",\"fields\":{\"value\":\"\"}}"]

 */
}
